[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Issa Memari", email = "issa.memari@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

